version: '3'
services:
  hello-service:
    build:
      context: ./hello-service
      dockerfile: ./Dockerfile
    environment:
    - HELLO_SERVICE_PORT=80
    deploy:
      replicas: 1
    expose:
    - 80
  world-service:
    build:
      context: ./world-service
      dockerfile: ./Dockerfile
    environment:
    - WORLD_SERVICE_PORT=80
    deploy:
      replicas: 1
    expose:
    - 80
  greeting-service:
    build:
      context: ./greeting-service
      dockerfile: ./Dockerfile
    ports:
      - 80:8090
    environment:
    - PORT=8090
    - HELLO_SERVICE_HOST_PREFIX=https://hello-service.internal
    - WORLD_SERVICE_HOST_PREFIX=https://world-service.internal
    depends_on:
      - hello-service
      - world-service
    deploy:
      replicas: 1
